name: build push docker image

permissions:
  contents: read
  packages: write
  statuses: write
  checks: write

on:
  push:
    branches:
      - main

jobs:
  docker-image:
    runs-on: ubuntu-latest
    container:
      options: --privileged
      credentials:
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_PASSWORD }}
    steps:
      - name: Login to Forgejo
        uses: docker/login-action@v3
        with:
          registry: forgejo.duckpond.dev
          username: ${{ github.actor }}
          password: ${{ secrets.FORGEJO_PUSH_REGISTRY }}

      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU for multiarch
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64
            linux/arm64                        
          push: true
          tags: |
            forgejo.duckpond.dev/enso/mqttui:1.4.2
            forgejo.duckpond.dev/enso/mqttui:latest