name: build push docker image

on:
  push:
    branches:
      - main

jobs:
  docker-image:
    runs-on: ubuntu-latest
    container:
      options: --privileged
      credentials:
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_PASSWORD }}
    steps:
      - shell: bash
        name: Install docker-ce
        run: |
          install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          chmod a+r /etc/apt/keyrings/docker.gpg
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            tee /etc/apt/sources.list.d/docker.list > /dev/null
          apt-get update -qq
          apt-get  -q install -qq \
            containerd.io \
            docker-ce \
            docker-ce-cli \
            ;
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU for multiarch
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64
            linux/arm64                        
          push: true
          tags: |
            sofiaurora/mqttui:1.3.0
            sofiaurora/mqttui:latest